package movies.server;

import movies.server.movie.Movie;
import movies.server.movie.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MoviesServerApplication implements CommandLineRunner {

    @Autowired
    private final MovieRepository movieRepository;

    public MoviesServerApplication(MovieRepository movieRepository) {
        this.movieRepository = movieRepository;
    }

    @Override
    public void run(String...args) throws Exception {

        movieRepository.save(new Movie("Inception", "https://m.media-amazon.com/images/I/7106uLYY2LL._AC_SL1111_.jpg", "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster."));
        movieRepository.save(new Movie("Arcane","https://fwcdn.pl/fpo/36/28/873628/7983711.3.jpg", "Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart."));
        movieRepository.save(new Movie("Jurassic World", "https://a.allegroimg.com/original/116f00/864929394e75a2d65d441b8e0c54/JURASSIC-WORLD-UPADLE-KROLESTWO-DVD", "Jurassic World has been running with great success for more than a decade in the wake of the disaster that haunted the island twenty-two years ago. The park's geneticists have once again broken scientific and ethical boundaries in order to raise attendance for the park, now experiencing a decline in happy customers. Convinced that the new attraction will bring in many more people, but having crossed the line once again, the results may be devastating."));
        movieRepository.save(new Movie("Blade Runner","https://static.wikia.nocookie.net/bladerunner/images/5/53/Blade_Runner_poster.jpg","Early in the 21st Century, THE TYRELL CORPORATION advanced Robot evolution into the NEXUS phase – a being virtually identical to a human – known as a Replicant.\nThe NEXUS 6 Replicants were superior in strength and agility, and at least equal in intelligence, to the genetic engineers who created them.\nReplicants were used Off-world as slave labor, in the hazardous exploration and colonization of other planets.\nAfter a bloody mutiny by a NEXUS 6 combat team in an Off-world colony, Replicants were declared illegal on earth – under penalty of death.\nSpecial police squads – BLADE RUNNER UNITS – had orders to shoot to kill, upon detection, any trespassing Replicant.\nThis was not called execution. It was called retirement."));
        movieRepository.save(new Movie("Spiderman: Into The Spiderverse","https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_FMjpg_UX1000_.jpg","Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities."));
        movieRepository.save(new Movie("Mad Max: Fury Road","https://fwcdn.pl/fpo/57/47/95747/7683234.3.jpg","In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max."));
        movieRepository.save(new Movie("Blade Runner 2049","https://fwcdn.pl/fpo/07/98/630798/7801880.3.jpg","Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years."));
        movieRepository.save(new Movie("Avengers: Endgame","https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg","After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store."));
        movieRepository.save(new Movie("Inception", "https://m.media-amazon.com/images/I/7106uLYY2LL._AC_SL1111_.jpg", "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster."));
        movieRepository.save(new Movie("Arcane","https://fwcdn.pl/fpo/36/28/873628/7983711.3.jpg", "Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart."));
        movieRepository.save(new Movie("Jurassic World", "https://a.allegroimg.com/original/116f00/864929394e75a2d65d441b8e0c54/JURASSIC-WORLD-UPADLE-KROLESTWO-DVD", "Jurassic World has been running with great success for more than a decade in the wake of the disaster that haunted the island twenty-two years ago. The park's geneticists have once again broken scientific and ethical boundaries in order to raise attendance for the park, now experiencing a decline in happy customers. Convinced that the new attraction will bring in many more people, but having crossed the line once again, the results may be devastating."));
        movieRepository.save(new Movie("Blade Runner","https://static.wikia.nocookie.net/bladerunner/images/5/53/Blade_Runner_poster.jpg","Early in the 21st Century, THE TYRELL CORPORATION advanced Robot evolution into the NEXUS phase – a being virtually identical to a human – known as a Replicant.\nThe NEXUS 6 Replicants were superior in strength and agility, and at least equal in intelligence, to the genetic engineers who created them.\nReplicants were used Off-world as slave labor, in the hazardous exploration and colonization of other planets.\nAfter a bloody mutiny by a NEXUS 6 combat team in an Off-world colony, Replicants were declared illegal on earth – under penalty of death.\nSpecial police squads – BLADE RUNNER UNITS – had orders to shoot to kill, upon detection, any trespassing Replicant.\nThis was not called execution. It was called retirement."));
        movieRepository.save(new Movie("Spiderman: Into The Spiderverse","https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_FMjpg_UX1000_.jpg","Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities."));
        movieRepository.save(new Movie("Mad Max: Fury Road","https://fwcdn.pl/fpo/57/47/95747/7683234.3.jpg","In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max."));
        movieRepository.save(new Movie("Blade Runner 2049","https://fwcdn.pl/fpo/07/98/630798/7801880.3.jpg","Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years."));
        movieRepository.save(new Movie("Avengers: Endgame","https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg","After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store."));
        movieRepository.save(new Movie("Inception", "https://m.media-amazon.com/images/I/7106uLYY2LL._AC_SL1111_.jpg", "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster."));
        movieRepository.save(new Movie("Arcane","https://fwcdn.pl/fpo/36/28/873628/7983711.3.jpg", "Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart."));
        movieRepository.save(new Movie("Jurassic World", "https://a.allegroimg.com/original/116f00/864929394e75a2d65d441b8e0c54/JURASSIC-WORLD-UPADLE-KROLESTWO-DVD", "Jurassic World has been running with great success for more than a decade in the wake of the disaster that haunted the island twenty-two years ago. The park's geneticists have once again broken scientific and ethical boundaries in order to raise attendance for the park, now experiencing a decline in happy customers. Convinced that the new attraction will bring in many more people, but having crossed the line once again, the results may be devastating."));
        movieRepository.save(new Movie("Blade Runner","https://static.wikia.nocookie.net/bladerunner/images/5/53/Blade_Runner_poster.jpg","Early in the 21st Century, THE TYRELL CORPORATION advanced Robot evolution into the NEXUS phase – a being virtually identical to a human – known as a Replicant.\nThe NEXUS 6 Replicants were superior in strength and agility, and at least equal in intelligence, to the genetic engineers who created them.\nReplicants were used Off-world as slave labor, in the hazardous exploration and colonization of other planets.\nAfter a bloody mutiny by a NEXUS 6 combat team in an Off-world colony, Replicants were declared illegal on earth – under penalty of death.\nSpecial police squads – BLADE RUNNER UNITS – had orders to shoot to kill, upon detection, any trespassing Replicant.\nThis was not called execution. It was called retirement."));
        movieRepository.save(new Movie("Spiderman: Into The Spiderverse","https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_FMjpg_UX1000_.jpg","Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities."));
        movieRepository.save(new Movie("Mad Max: Fury Road","https://fwcdn.pl/fpo/57/47/95747/7683234.3.jpg","In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max."));
        movieRepository.save(new Movie("Blade Runner 2049","https://fwcdn.pl/fpo/07/98/630798/7801880.3.jpg","Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years."));
        movieRepository.save(new Movie("Avengers: Endgame","https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg","After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store."));
    }

    public static void main(String[] args) {
        SpringApplication.run(MoviesServerApplication.class, args);
    }



}
